### PR TITLE
Bump version ahead of next release

### PR DESCRIPTION
**Pull request by woahdae**

### CODE REVIEW

**Comment by dblock** [comment]
No need for a code review for something like this @woahdae if you're doing a release ;) Thanks!

**Comment by dblock** [comment]
I think this should have been a 0.2.0 since it changes the "api".

**Comment by woahdae** [comment]
I saw no changes to either the public or private interfaces of the project, so I'd say there were no API changes. I didn't see a note on versioning, but IMHO if it's pre-1.0 the semantic versioning spec states that the API is unstable and can change at any time. It's unclear how to bump versions in that situation, but I could agree that API changes would require a minor bump. Again, I didn't see any though.

There is a change in behavior, but I'd classify it as a bugfix. Evidence of such is there were existing tests asserting the case of including a header with the title "Ignore Me" and a body with text, then asserting the body was included. However, the case of including the header and body and asserting "Ignore Me" was *not* in the text part was not written. The presence of "ignore me" in the test body text strongly implies the expected behavior was for the "ignore me" title to be ignored.

Also, request for the same issue was filed, see #2.

Thanks for pulling that in! I wasn't sure if you would have preferred two commits for the changelog or one (i.e. one to set it "current" before release, then another to add the next release version slot).

**Comment by dblock** [comment]
All this makes sense. Thanks for contributing and doing a release! Run with it.

**Pull request merged**
